User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'DeprecatePythonPath - experiment'
> conda --version
> pyenv root
> python3.7 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Python interpreter path: /usr/bin/python3.8
Starting Jedi Python language engine.
Error 2021-03-10 04:09:37: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): 파일 'vscode-remote://ssh-remote+27.96.134.7/root/.config/Code/User/settings.json'(Error: 존재하지 않는 파일 'vscode-remote://ssh-remote+27.96.134.7/root/.config/Code/User/settings.json'을(를) 확인할 수 없습니다.)을(를) 읽을 수 없음
	at _handleError (/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostProcess.js:87:151863)
	at async y.readText (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:298390)
	at async p.doesFileNeedToBeFixed (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:481011)
	at async /root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480138
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480084)
	at async p.updateTestSettings (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:479711)] {
  code: 'FileNotFound'
}
Error 2021-03-10 04:09:37: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): 파일 'vscode-remote://ssh-remote+27.96.134.7/root/moviesajo/.vscode/settings.json'(Error: 존재하지 않는 파일 'vscode-remote://ssh-remote+27.96.134.7/root/moviesajo/.vscode/settings.json'을(를) 확인할 수 없습니다.)을(를) 읽을 수 없음
	at _handleError (/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostProcess.js:87:151863)
	at async y.readText (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:298390)
	at async p.doesFileNeedToBeFixed (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:481011)
	at async /root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480138
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480084)
	at async p.updateTestSettings (/root/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:479711)] {
  code: 'FileNotFound'
}
> conda --version
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/completion.py
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/completion.py
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/moviesajo/moviesajo/__init__.py
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text ~/moviesajo/moviesajo/__init__.py
cwd: ~/moviesajo
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> /usr/bin/python3.8 ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
Error 2021-03-10 04:09:43: stderr jediProxy Error (stderr) /root/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

